       01 G-DUS001.
         02 a-avtor-ownkey LINE 10 COL 42 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC Z(6) USING avtor-ownkey.
         02 a-avtor-naziv LINE 12 COL 42 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC X(20) USING avtor-naziv.
         02 a-avtor-vrsta LINE 14 COL 42 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC Z USING avtor-vrsta.
         02 a-vrsta-naziv LINE 14 COL 44 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC X(15) USING vrsta-naziv.
         02 a-avtor-koliko LINE 15 COL 56 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC Z(6) TO avtor-koliko.
         02 LINE 8 COL 30 VALUE "ÚÄÄ A v t o r   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿".
         02 LINE 9 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                  ".
         02 COL 65 VALUE "³".
         02 LINE 10 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "   [ifra : ".
         02 COL 48 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                 ".
         02 COL 65 VALUE "³".
         02 LINE 11 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                  ".
         02 COL 65 VALUE "³".
         02 LINE 12 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "   Naziv : ".
         02 COL 62 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "   ".
         02 COL 65 VALUE "³".
         02 LINE 13 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                  ".
         02 COL 65 VALUE "³".
         02 LINE 14 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "   Vrsta : ".
         02 COL 43 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       " ".
         02 COL 59 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "      ".
         02 COL 65 VALUE "³".
         02 LINE 15 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                         ".
         02 COL 62 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "   ".
         02 COL 65 VALUE "³".
         02 LINE 16 COL 30 VALUE "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ".
