       01 G-IZP003.
         02 a-zbori-ownkey LINE 13 COL 42 BACKGROUND-COLOR 2
       FOREGROUND-COLOR 0 PIC ZZ USING zbori-ownkey.
         02 a-zbori-naziv LINE 13 COL 45 BACKGROUND-COLOR 2
       FOREGROUND-COLOR 0 PIC X(20) USING zbori-naziv.
         02 a-w-vrsta LINE 15 COL 43 BACKGROUND-COLOR 2 FOREGROUND-COLOR
       0 PIC Z USING w-vrsta.
         02 a-vrsta-naziv LINE 15 COL 45 BACKGROUND-COLOR 2
       FOREGROUND-COLOR 0 PIC X(10) USING vrsta-naziv.
         02 LINE 11 COL 31 VALUE "здд Izpis PESMI дддддддддддддддддддддд
      -"дд©".
         02 LINE 12 COL 31 VALUE "Ё".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "
      -"                               ".
         02 COL 71 VALUE "Ё".
         02 LINE 13 COL 31 VALUE "Ё".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "   zbor
      -": ".
         02 COL 44 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE " ".
         02 COL 65 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "      ".
         02 COL 71 VALUE "Ё".
         02 LINE 14 COL 31 VALUE "Ё".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "
      -"                               ".
         02 COL 71 VALUE "Ё".
         02 LINE 15 COL 31 VALUE "Ё".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "  seznam
      -" : ".
         02 COL 44 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE " ".
         02 COL 55 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "
      -"        ".
         02 COL 71 VALUE "Ё".
         02 LINE 16 COL 31 VALUE "Ё".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "
      -"                               ".
         02 COL 71 VALUE "Ё".
         02 LINE 17 COL 31 VALUE "юддддддддддддддддддддддддддддддддддддд
      -"дды".
