       01 G-MELODIJA.
         02 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 HIGHLIGHT
       BLANK SCREEN.
         02 LINE 1 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "                зддд© здд© з©  з© здд   з© Ё                   P
      -"iv{ka 6         ".
         02 LINE 2 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "    Copyright   Ё     Ё  Ё Ёю©зыЁ цд  Ё Ёю©Ё                   6
      -"230 Postojna    ".
         02 LINE 3 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "                юддды юдды Ё юы Ё Ё   Ё Ё юы                   t
      -"el. 067/25-038  ".
         02 LINE 4 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "                 Ё  Ё з© ЁЁзызд©     з дбдздзд здЁ
      -"                ".
         02 LINE 5 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "                 ю©зыЁЁю©Ёц╢ Ё Ё     ю© Ё ц Ёз©ц Ё
      -"                ".
         02 LINE 6 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "                  юы ЁЁ юыЁю©юды     ды Ё юдюдыюдюд
      -"                ".
         02 LINE 7 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      -"ддддддддддддддд©".
         02 LINE 8 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 18 VALUE "ш  ъъ            ш      ш
      -"                ".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 9 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 9 VALUE "шшшш  ш  ш шшшш шшшшш шш  ш      ш  ш шшшшш шшш
      -"шш шшшшш ш              ".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 10 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 9 VALUE "ш   ш ш  ш ш    ш   ш шшш ш      ш шш ш   ш ш
      -"   ш   ш ш              ".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 11 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 9 VALUE "ш   ш ш  ш шшшш шшшшш ш шшш      шшш  шшшшш шшш
      -"   ш   ш ш              ".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 12 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 9 VALUE "ш   ш ш  ш    ш ш   ш ш  шш      ш шш ш   ш ш
      -"   ш   ш ш              ".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 13 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 9 VALUE "ш   ш шшшш шшшш ш   ш ш  шш      ш  ш ш   ш ш
      -"   шшшшш ш              ".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 14 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 9 VALUE "шшшш                ш ш             ш     ш ш
      -"         шшшшш          ".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 15 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 16 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 7 VALUE "з".
         02 COL 8 BACKGROUND-COLOR 3 VALUE "д©".
         02 COL 14 VALUE "з".
         02 COL 15 BACKGROUND-COLOR 3 VALUE "д©".
         02 COL 18 VALUE "з".
         02 COL 19 BACKGROUND-COLOR 3 VALUE "дддддд©".
         02 COL 27 VALUE "з".
         02 COL 28 BACKGROUND-COLOR 3 VALUE "д©".
         02 COL 36 VALUE "з".
         02 COL 37 BACKGROUND-COLOR 3 VALUE "дддддд©".
         02 COL 45 VALUE "з".
         02 COL 46 BACKGROUND-COLOR 3 VALUE "ддддд©".
         02 COL 54 VALUE "з".
         02 COL 55 BACKGROUND-COLOR 3 VALUE "д©".
         02 COL 63 VALUE "з".
         02 COL 64 BACKGROUND-COLOR 3 VALUE "д©".
         02 COL 67 VALUE "з".
         02 COL 68 BACKGROUND-COLOR 3 VALUE "дддддд©".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 17 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 7 VALUE "Ё".
         02 COL 8 BACKGROUND-COLOR 3 VALUE " ю".
         02 COL 10 VALUE "©  з".
         02 COL 14 BACKGROUND-COLOR 3 VALUE "ы Ё".
         02 COL 18 VALUE "Ё".
         02 COL 19 BACKGROUND-COLOR 3 VALUE " з".
         02 COL 21 VALUE "дддды Ё".
         02 COL 28 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 36 VALUE "Ё".
         02 COL 37 BACKGROUND-COLOR 3 VALUE " здд© Ё".
         02 COL 45 VALUE "Ё".
         02 COL 46 BACKGROUND-COLOR 3 VALUE " з".
         02 COL 48 VALUE "д©".
         02 COL 50 BACKGROUND-COLOR 3 VALUE " ю©".
         02 COL 54 VALUE "Ё".
         02 COL 55 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 63 VALUE "Ё".
         02 COL 64 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 67 VALUE "Ё".
         02 COL 68 BACKGROUND-COLOR 3 VALUE " з".
         02 COL 70 VALUE "дд©".
         02 COL 73 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 18 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 7 VALUE "Ё".
         02 COL 8 BACKGROUND-COLOR 3 VALUE "  ю".
         02 COL 11 VALUE "дд".
         02 COL 13 BACKGROUND-COLOR 3 VALUE "ы  Ё".
         02 COL 18 VALUE "Ё".
         02 COL 19 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 27 VALUE "Ё".
         02 COL 28 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 36 VALUE "Ё".
         02 COL 37 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 41 BACKGROUND-COLOR 3 VALUE "Ё Ё".
         02 COL 45 VALUE "Ё".
         02 COL 46 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 49 VALUE "ю©".
         02 COL 51 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 54 VALUE "Ё".
         02 COL 55 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 63 VALUE "Ё".
         02 COL 64 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 67 VALUE "Ё".
         02 COL 68 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 72 VALUE "Ё".
         02 COL 73 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 19 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 7 VALUE "Ё".
         02 COL 8 BACKGROUND-COLOR 3 VALUE "        Ё".
         02 COL 18 VALUE "Ё".
         02 COL 19 BACKGROUND-COLOR 3 VALUE " юдд©".
         02 COL 27 VALUE "Ё".
         02 COL 28 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 36 VALUE "Ё".
         02 COL 37 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 41 BACKGROUND-COLOR 3 VALUE "Ё Ё".
         02 COL 45 VALUE "Ё".
         02 COL 46 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 50 VALUE "Ё".
         02 COL 51 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 54 VALUE "Ё".
         02 COL 55 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 63 VALUE "Ё".
         02 COL 64 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 67 VALUE "Ё".
         02 COL 68 BACKGROUND-COLOR 3 VALUE " ю".
         02 COL 70 VALUE "дды".
         02 COL 73 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 20 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 7 VALUE "Ё".
         02 COL 8 BACKGROUND-COLOR 3 VALUE " з©  з© Ё".
         02 COL 18 VALUE "Ё".
         02 COL 19 BACKGROUND-COLOR 3 VALUE " з".
         02 COL 21 VALUE "дды   Ё".
         02 COL 28 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 36 VALUE "Ё".
         02 COL 37 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 41 BACKGROUND-COLOR 3 VALUE "Ё Ё".
         02 COL 45 VALUE "Ё".
         02 COL 46 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 50 VALUE "Ё".
         02 COL 51 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 54 VALUE "Ё".
         02 COL 55 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 63 VALUE "Ё".
         02 COL 64 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 67 VALUE "Ё".
         02 COL 68 BACKGROUND-COLOR 3 VALUE " здд© Ё".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 21 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 7 VALUE "Ё".
         02 COL 8 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 10 VALUE "ю".
         02 COL 11 BACKGROUND-COLOR 3 VALUE "дды".
         02 COL 14 VALUE "Ё".
         02 COL 15 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 18 VALUE "Ё".
         02 COL 19 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 27 VALUE "Ё".
         02 COL 28 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 36 VALUE "Ё".
         02 COL 37 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 41 BACKGROUND-COLOR 3 VALUE "Ё Ё".
         02 COL 45 VALUE "Ё".
         02 COL 46 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 49 VALUE "з".
         02 COL 50 BACKGROUND-COLOR 3 VALUE "ы Ё".
         02 COL 54 VALUE "Ё".
         02 COL 55 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 58 VALUE "з".
         02 COL 59 BACKGROUND-COLOR 3 VALUE "д©".
         02 COL 63 VALUE "Ё".
         02 COL 64 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 67 VALUE "Ё".
         02 COL 68 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 72 VALUE "Ё".
         02 COL 73 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 22 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 7 VALUE "Ё".
         02 COL 8 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 14 VALUE "Ё".
         02 COL 15 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 18 VALUE "Ё".
         02 COL 19 BACKGROUND-COLOR 3 VALUE " юдддд©".
         02 COL 27 VALUE "Ё".
         02 COL 28 BACKGROUND-COLOR 3 VALUE " юдддд©".
         02 COL 36 VALUE "Ё".
         02 COL 37 BACKGROUND-COLOR 3 VALUE " юдды Ё".
         02 COL 45 VALUE "Ё".
         02 COL 46 BACKGROUND-COLOR 3 VALUE " юды з".
         02 COL 52 VALUE "ы Ё".
         02 COL 55 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 58 VALUE "Ё".
         02 COL 59 BACKGROUND-COLOR 3 VALUE " юдды Ё".
         02 COL 67 VALUE "Ё".
         02 COL 68 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 72 VALUE "Ё".
         02 COL 73 BACKGROUND-COLOR 3 VALUE " Ё".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 23 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "Ё".
         02 COL 7 VALUE "юды    юды юдддддды юдддддды юдддддды юддддды
      -"юды юдддддды юды  юды     ".
         02 COL 80 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "Ё".
         02 LINE 24 COL 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE
       "юддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      -"ддддддддддддддды".
