       01 G-VINKO.
         02 LINE 5 COL 17 VALUE "ษออออออออออออออออออออออออออออออออออออออ
      -"อออออป".
         02 LINE 6 COL 17 VALUE "บ ".
         02 COL 19 BLINK REVERSE-VIDEO VALUE "
      -"               ".
         02 COL 61 VALUE "บ".
         02 LINE 7 COL 17 VALUE "บ ".
         02 COL 19 BLINK REVERSE-VIDEO VALUE "  N A P A ^ N A   I N S T
      -"A L A C I J A  ".
         02 COL 61 VALUE "บ".
         02 LINE 8 COL 17 VALUE "บ ".
         02 COL 19 BLINK REVERSE-VIDEO VALUE "
      -"               ".
         02 COL 61 VALUE "บ".
         02 LINE 9 COL 17 VALUE "บ
      -"     บ".
         02 LINE 10 COL 17 VALUE "บ           ".
         02 COL 29 HIGHLIGHT VALUE "stegel vinko".
         02 COL 61 VALUE "บ".
         02 LINE 11 COL 17 VALUE "บ           piv{ka 6, postojna
      -"      บ".
         02 LINE 12 COL 17 VALUE "บ           66230 postojna
      -"      บ".
         02 LINE 13 COL 17 VALUE "บ
      -"      บ".
         02 LINE 14 COL 17 VALUE "บ           ".
         02 COL 29 HIGHLIGHT VALUE "tel. 067 22-753".
         02 COL 61 VALUE "บ".
         02 LINE 15 COL 17 VALUE "บ
      -"      บ".
         02 LINE 16 COL 17 VALUE "ศอออออออออออออออออออออออออออออออออออออ
      -"ออออออผ".
