       01 G-DUS002.
         02 a-zbori-ownkey LINE 9 COL 28 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC ZZ USING zbori-ownkey.
         02 a-zbori-naziv LINE 9 COL 31 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC X(20) USING zbori-naziv.
         02 a-pesmi-stevilka LINE 11 COL 28 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC Z(5) USING pesmi-stevilka.
         02 a-pesmi-naziv LINE 11 COL 34 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC X(40) USING pesmi-naziv.
         02 a-pesmi-verz LINE 13 COL 34 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC X(20) USING pesmi-verz.
         02 a-pesmi-osnova LINE 15 COL 28 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC Z(6) USING pesmi-osnova.
         02 a-osnova-naziv LINE 15 COL 35 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC X(20) USING osnova-naziv.
         02 a-pesmi-prired LINE 17 COL 28 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC Z(6) USING pesmi-prired.
         02 a-prired-naziv LINE 17 COL 35 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC X(20) USING prired-naziv.
         02 a-pesmi-opomba LINE 19 COL 28 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC X(31) USING pesmi-opomba.
         02 LINE 7 COL 15 VALUE "ÚÄÄ S k l a d b a ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
      -"ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿".
         02 LINE 8 COL 15 VALUE "³".
         02 COL 16 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                                           ".
         02 COL 75 VALUE "³".
         02 LINE 9 COL 15 VALUE "³".
         02 COL 16 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "     Zbor : ".
         02 COL 30 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       " ".
         02 COL 51 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                        ".
         02 COL 75 VALUE "³".
         02 LINE 10 COL 15 VALUE "³".
         02 COL 16 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                                           ".
         02 COL 75 VALUE "³".
         02 LINE 11 COL 15 VALUE "³".
         02 COL 16 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "  Skladba : ".
         02 COL 33 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       " ".
         02 COL 74 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       " ".
         02 COL 75 VALUE "³".
         02 LINE 12 COL 15 VALUE "³".
         02 COL 16 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                                           ".
         02 COL 75 VALUE "³".
         02 LINE 13 COL 15 VALUE "³".
         02 COL 16 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "     Verz :       ".
         02 COL 54 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                     ".
         02 COL 75 VALUE "³".
         02 LINE 14 COL 15 VALUE "³".
         02 COL 16 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                                           ".
         02 COL 75 VALUE "³".
         02 LINE 15 COL 15 VALUE "³".
         02 COL 16 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "   Pesnik : ".
         02 COL 34 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       " ".
         02 COL 55 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                    ".
         02 COL 75 VALUE "³".
         02 LINE 16 COL 15 VALUE "³".
         02 COL 16 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                                           ".
         02 COL 75 VALUE "³".
         02 LINE 17 COL 15 VALUE "³".
         02 COL 16 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       " Uglasbil : ".
         02 COL 34 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       " ".
         02 COL 55 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                    ".
         02 COL 75 VALUE "³".
         02 LINE 18 COL 15 VALUE "³".
         02 COL 16 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                                           ".
         02 COL 75 VALUE "³".
         02 LINE 19 COL 15 VALUE "³".
         02 COL 16 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "   Opomba : ".
         02 COL 59 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                ".
         02 COL 75 VALUE "³".
         02 LINE 20 COL 15 VALUE "³".
         02 COL 16 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                                           ".
         02 COL 75 VALUE "³".
         02 LINE 21 COL 15 VALUE "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
      -"ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ".
