       01 G-DUS003.
         02 a-zbori-ownkey LINE 10 COL 43 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC ZZ USING zbori-ownkey.
         02 a-zbori-naziv LINE 12 COL 43 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC X(20) USING zbori-naziv.
         02 a-zbori-krnaz LINE 14 COL 43 BACKGROUND-COLOR 6
       FOREGROUND-COLOR 3 HIGHLIGHT PIC X(5) USING zbori-krnaz.
         02 LINE 8 COL 30 VALUE "ÚÄÄ Z b o r i  ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿".
         02 LINE 9 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                  ".
         02 COL 65 VALUE "³".
         02 LINE 10 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "   [ifra  : ".
         02 COL 45 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                    ".
         02 COL 65 VALUE "³".
         02 LINE 11 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                  ".
         02 COL 65 VALUE "³".
         02 LINE 12 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "   Naziv  : ".
         02 COL 63 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "  ".
         02 COL 65 VALUE "³".
         02 LINE 13 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                  ".
         02 COL 65 VALUE "³".
         02 LINE 14 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "   Oznaka : ".
         02 COL 48 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                 ".
         02 COL 65 VALUE "³".
         02 LINE 15 COL 30 VALUE "³".
         02 COL 31 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE
       "                                  ".
         02 COL 65 VALUE "³".
         02 LINE 16 COL 30 VALUE "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ".
