       01 G-IZP002.
         02 a-w-vrsta LINE 13 COL 50 BACKGROUND-COLOR 2 FOREGROUND-COLOR
       0 PIC Z USING w-vrsta.
         02 a-vrsta-naziv LINE 13 COL 52 BACKGROUND-COLOR 2
       FOREGROUND-COLOR 0 PIC X(10) USING vrsta-naziv.
         02 LINE 11 COL 31 VALUE "здд Izpis AVTORJEV ддддддддддддддддддд
      -"дд©".
         02 LINE 12 COL 31 VALUE "Ё".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "
      -"                               ".
         02 COL 71 VALUE "Ё".
         02 LINE 13 COL 31 VALUE "Ё".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "  Vrsta
      -"seznama : ".
         02 COL 51 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE " ".
         02 COL 62 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "
      -" ".
         02 COL 71 VALUE "Ё".
         02 LINE 14 COL 31 VALUE "Ё".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "
      -"                               ".
         02 COL 71 VALUE "Ё".
         02 LINE 15 COL 31 VALUE "Ё".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "
      -"                               ".
         02 COL 71 VALUE "Ё".
         02 LINE 16 COL 31 VALUE "Ё".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "
      -"                               ".
         02 COL 71 VALUE "Ё".
         02 LINE 17 COL 31 VALUE "юддддддддддддддддддддддддддддддддддддд
      -"дды".
