       01 G-IZP006.
         02 a-zbori-ownkey LINE 13 COL 42 BACKGROUND-COLOR 2
       FOREGROUND-COLOR 0 PIC ZZ USING zbori-ownkey.
         02 a-zbori-naziv LINE 13 COL 45 BACKGROUND-COLOR 2
       FOREGROUND-COLOR 0 PIC X(20) USING zbori-naziv.
         02 a-avtor-ownkey LINE 15 COL 42 BACKGROUND-COLOR 2
       FOREGROUND-COLOR 0 PIC Z(6) USING avtor-ownkey.
         02 a-avtor-naziv LINE 15 COL 49 BACKGROUND-COLOR 2
       FOREGROUND-COLOR 0 PIC X(20) USING avtor-naziv.
         02 LINE 11 COL 31 VALUE "ÚÄÄ Izpis PESNIK-ZBOR-SKLADBA ÄÄÄÄÄÄÄÄ
      -"ÄÄ¿".
         02 LINE 12 COL 31 VALUE "³".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "
      -"                               ".
         02 COL 71 VALUE "³".
         02 LINE 13 COL 31 VALUE "³".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "   Zbor
      -": ".
         02 COL 44 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE " ".
         02 COL 65 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "      ".
         02 COL 71 VALUE "³".
         02 LINE 14 COL 31 VALUE "³".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "
      -"                               ".
         02 COL 71 VALUE "³".
         02 LINE 15 COL 31 VALUE "³".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE " Pesnik
      -": ".
         02 COL 48 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE " ".
         02 COL 69 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "  ".
         02 COL 71 VALUE "³".
         02 LINE 16 COL 31 VALUE "³".
         02 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE "
      -"                               ".
         02 COL 71 VALUE "³".
         02 LINE 17 COL 31 VALUE "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
      -"ÄÄÙ".
