       01 G-MEN003.
         02 LINE 7 COL 26 VALUE "ÚÄÄÄÄ Vzdr`evanje ÄÄÄÄÄÄÄÄÄÄ¿".
         02 LINE 8 COL 26 VALUE "³".
         02 COL 27 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE "
      -"                   ".
         02 COL 54 VALUE "³".
         02 LINE 9 COL 26 VALUE "³".
         02 COL 27 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE " ".
         02 COL 28 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 VALUE "°°°".
         02 COL 31 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE " Shranje
      -"vanje podatkov ".
         02 COL 54 VALUE "³".
         02 LINE 10 COL 26 VALUE "³".
         02 COL 27 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE "
      -"                   ".
         02 COL 54 VALUE "³".
         02 LINE 11 COL 26 VALUE "³".
         02 COL 27 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE " ".
         02 COL 28 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 VALUE "°°°".
         02 COL 31 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE " Spremem
      -"ba datuma      ".
         02 COL 54 VALUE "³".
         02 LINE 12 COL 26 VALUE "³".
         02 COL 27 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE "
      -"                   ".
         02 COL 54 VALUE "³".
         02 LINE 13 COL 26 VALUE "³".
         02 COL 27 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE " ".
         02 COL 28 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 VALUE "°°°".
         02 COL 31 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE " Spremem
      -"ba ure         ".
         02 COL 54 VALUE "³".
         02 LINE 14 COL 26 VALUE "³".
         02 COL 27 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE "
      -"                   ".
         02 COL 54 VALUE "³".
         02 LINE 15 COL 26 VALUE "³".
         02 COL 27 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE " ".
         02 COL 28 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 VALUE "°°°".
         02 COL 31 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE " Vra~anj
      -"e podatkov     ".
         02 COL 54 VALUE "³".
         02 LINE 16 COL 26 VALUE "³".
         02 COL 27 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE "
      -"                   ".
         02 COL 54 VALUE "³".
         02 LINE 17 COL 26 VALUE "³                           ³".
         02 LINE 18 COL 26 VALUE "³                           ³".
         02 LINE 19 COL 26 VALUE "³                           ³".
         02 LINE 20 COL 26 VALUE "³                           ³".
         02 LINE 21 COL 26 VALUE "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ".
