       01 G-OKVLIS50.
         02 LINE 5 COL 9 VALUE "ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
      -"ÄÄÄÄÄÄÄÄÄÄÄÄ¿".
         02 LINE 6 COL 9 VALUE "³".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                           ".
         02 COL 61 VALUE "³".
         02 LINE 7 COL 9 VALUE "ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
      -"ÄÄÄÄÄÄÄÄÄÄÄÄ´".
         02 LINE 8 COL 9 VALUE "³".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                           ".
         02 COL 61 VALUE "³".
         02 LINE 9 COL 9 VALUE "³".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                           ".
         02 COL 61 VALUE "³".
         02 LINE 10 COL 9 VALUE "³".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                           ".
         02 COL 61 VALUE "³".
         02 LINE 11 COL 9 VALUE "³".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                           ".
         02 COL 61 VALUE "³".
         02 LINE 12 COL 9 VALUE "³".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                           ".
         02 COL 61 VALUE "³".
         02 LINE 13 COL 9 VALUE "³".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                           ".
         02 COL 61 VALUE "³".
         02 LINE 14 COL 9 VALUE "³".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                           ".
         02 COL 61 VALUE "³".
         02 LINE 15 COL 9 VALUE "³".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                           ".
         02 COL 61 VALUE "³".
         02 LINE 16 COL 9 VALUE "³".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                           ".
         02 COL 61 VALUE "³".
         02 LINE 17 COL 9 VALUE "³".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                           ".
         02 COL 61 VALUE "³".
         02 LINE 18 COL 9 VALUE "³".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                           ".
         02 COL 61 VALUE "³".
         02 LINE 19 COL 9 VALUE "³".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                           ".
         02 COL 61 VALUE "³".
         02 LINE 20 COL 9 VALUE "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
      -"ÄÄÄÄÄÄÄÄÄÄÄÄÄÙ".
