       01 G-OKVLIS60.
         02 LINE 5 COL 9 VALUE "зддддддддддддддддддддддддддддддддддддддд
      -"ддддддддддддддддддддд©".
         02 LINE 6 COL 9 VALUE "Ё".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                                    ".
         02 COL 70 VALUE "Ё".
         02 LINE 7 COL 9 VALUE "цддддддддддддддддддддддддддддддддддддддд
      -"ддддддддддддддддддддд╢".
         02 LINE 8 COL 9 VALUE "Ё".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                                    ".
         02 COL 70 VALUE "Ё".
         02 LINE 9 COL 9 VALUE "Ё".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                                    ".
         02 COL 70 VALUE "Ё".
         02 LINE 10 COL 9 VALUE "Ё".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                                    ".
         02 COL 70 VALUE "Ё".
         02 LINE 11 COL 9 VALUE "Ё".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                                    ".
         02 COL 70 VALUE "Ё".
         02 LINE 12 COL 9 VALUE "Ё".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                                    ".
         02 COL 70 VALUE "Ё".
         02 LINE 13 COL 9 VALUE "Ё".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                                    ".
         02 COL 70 VALUE "Ё".
         02 LINE 14 COL 9 VALUE "Ё".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                                    ".
         02 COL 70 VALUE "Ё".
         02 LINE 15 COL 9 VALUE "Ё".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                                    ".
         02 COL 70 VALUE "Ё".
         02 LINE 16 COL 9 VALUE "Ё".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                                    ".
         02 COL 70 VALUE "Ё".
         02 LINE 17 COL 9 VALUE "Ё".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                                    ".
         02 COL 70 VALUE "Ё".
         02 LINE 18 COL 9 VALUE "Ё".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                                    ".
         02 COL 70 VALUE "Ё".
         02 LINE 19 COL 9 VALUE "Ё".
         02 COL 10 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                                    ".
         02 COL 70 VALUE "Ё".
         02 LINE 20 COL 9 VALUE "юдддддддддддддддддддддддддддддддддддддд
      -"дддддддддддддддддддддды".
