       01 G-OKVLIS.
         02 LINE 5 COL 39 VALUE "ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
      -"ÄÄ¿".
         02 LINE 6 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 7 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 8 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 9 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 10 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 11 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 12 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 13 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 14 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 15 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 16 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 17 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 18 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 19 COL 39 VALUE "³".
         02 COL 40 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE "
      -"                                ".
         02 COL 80 VALUE "³".
         02 LINE 20 COL 39 VALUE "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
      -"ÄÄÄÙ".
