       01 G-REBILD.
         02 a-datoteka LINE 14 COL 37 PIC X(6) USING ws-datoteka.
         02 a-citanih LINE 14 COL 47 PIC Z(6) USING ws-citanih.
         02 LINE 12 COL 33 VALUE "зд ".
         02 COL 36 HIGHLIGHT VALUE "R E B U I L D ".
         02 COL 50 VALUE "ддддд©".
         02 LINE 13 COL 33 VALUE "Ё                     Ё".
         02 LINE 14 COL 33 VALUE "Ё                     Ё".
         02 LINE 15 COL 33 VALUE "Ё                     Ё".
         02 LINE 16 COL 33 VALUE "юддддддддддддддддддддды".
